### ISSUE TITLE
新版成功-可是出问题了

### ISSUE THREAD

**Issue by androidcn** [2van/baidumap-to-amap#2]
`
导入成功：荣超商务中心-地下车库 | 深圳市
已成功0个，15秒后导入下一个
导入成功：深圳福田星河COCO PARK地下停车场 | 深圳市
已成功0个，15秒后导入下一个
/Users/SlimBook/Downloads/baidumap-to-amap-main/node_modules/form-data/lib/form_data.js:226
  } else if (options.filename || value.name || value.path) {
                                       ^

TypeError: Cannot read property 'name' of undefined
    at FormData._getContentDisposition (/Users/SlimBook/Downloads/baidumap-to-amap-main/node_modules/form-data/lib/form_data.js:226:40)
    at FormData._multiPartHeader (/Users/SlimBook/Downloads/baidumap-to-amap-main/node_modules/form-data/lib/form_data.js:177:33)
    at FormData.append (/Users/SlimBook/Downloads/baidumap-to-amap-main/node_modules/form-data/lib/form_data.js:70:21)
    at appendFormValue (/Users/SlimBook/Downloads/baidumap-to-amap-main/node_modules/request/request.js:326:21)
    at Request.init (/Users/SlimBook/Downloads/baidumap-to-amap-main/node_modules/request/request.js:337:11)
    at new Request (/Users/SlimBook/Downloads/baidumap-to-amap-main/node_modules/request/request.js:127:8)
    at request (/Users/SlimBook/Downloads/baidumap-to-amap-main/node_modules/request/index.js:53:10)
    at file:///Users/SlimBook/Downloads/baidumap-to-amap-main/addDataToAmap.js:16:9
    at new Promise (<anonymous>)
    at addDataToAmap (file:///Users/SlimBook/Downloads/baidumap-to-amap-main/addDataToAmap.js:5:12)

`

**Comment by androidcn** [comment]
应该是
这个 

龙岗星河COCO PARK停车场 | 深圳市

出问题

**Comment by androidcn** [comment]
我猜是不是 用Chrome 获取cookie token 出错了
百度cookie没问题 能正常获取数据
但是POST给 高德就出问题
我把 获取流程发到您的邮箱avan4315#gmail.com了 请查收 !谢谢

**Comment by 2van** [comment]
@androidcn https://github.com/2van/baidumap-to-amap/pull/3 试试这个

**Comment by androidcn** [comment]
> @androidcn #3 试试这个

请兄弟 查看一下邮箱

avan4315#gmail.com

我发了 获取token的流程,不知道 是不是 这里 出错了

**Comment by 2van** [comment]
邮箱错了 @androidcn

**Comment by androidcn** [comment]
请问是哪个邮箱？
